### ISSUE TITLE
Display Author in Problem Description

### ISSUE THREAD

**Issue by rvantonder** [picoCTF/picoCTF-Platform-2#10]
It occurred to me that it would be nice to include an author field in problem.json that could be displayed in the problem description. Attribution and identification of problem authors are a nice-to-have.

**Comment by GroundPound** [comment]
Sounds reasonable. Let's discuss some of the details. What's the argument for adding a new field to the JSON description versus displaying it in the description field perhaps with specialized styling?

Would this be a required field? If so, do we support backwards comparability with problems that do not have an author field?

**Comment by cganas** [comment]
I think it is something that could be added to problem's JSON definition and should not be required. I think the tricky party would actually be displaying it somewhere that would consistently look good as not all problems would have the field.

I like the idea of putting it somewhere in the problem description with specialized styling.

**Comment by royragsdale** [comment]
The functionality to include challenge author exists in the new picoCTF-shell-manager packaging.

UI enhancement issue ported to [picoCTF-Web](https://github.com/picoCTF/picoCTF-web/issues/50) the actively maintained version.
