### ISSUE TITLE
Problem Linter

### ISSUE THREAD

**Issue by GroundPound** [picoCTF/picoCTF-Platform-2#13]
Since creating problems is often a collaborative process involving people not familiar with a framework, we could use a script that checks for common mistakes including malformed JSON or Python, directory structure, spelling, etc.

**Comment by royragsdale** [comment]
Closed and ported to [picoCTF-shell-manager](https://github.com/picoCTF/picoCTF-shell-manager/issues/79) the actively maintained version.
