### ISSUE TITLE
Registration Broken for Non-Advised Accounts

### ISSUE THREAD

**Issue by tim-becker** [picoCTF/picoCTF-Platform-2#15]
When trying to register as an undergraduate student, teacher, hobbyist, etc., the registration fails. The server seems to be expecting information about an adviser.
![bug](https://cloud.githubusercontent.com/assets/4476584/6515034/f8306a3c-c354-11e4-92bc-f3efcdfbb1af.png)

**Comment by GroundPound** [comment]
Duplicate of https://github.com/picoCTF/picoCTF-Platform-2/issues/12.
