### ISSUE TITLE
Optional Feature Support

### ISSUE THREAD

**Issue by GroundPound** [picoCTF/picoCTF-Platform-2#2]
Originally reported by @tim-becker. We would like to be able to disable features that may not apply to all competitions but exist in the code-base. Some examples of this include teacher accounts and problem feedback.

@tim-becker:
> The api has some checks to ensure that a feature is enabled when it receives a request. Client side changes will have to be more drastic. The "status" api call is currently returning information about what features are enabled. We should use these to adjust the UI accordingly.

Do we want the API to reject calls to such features or is just the UI changed?

**Comment by GroundPound** [comment]
Before working on this issue please contact a maintainer. Some solutions to this problem could introduce a great deal of complexity.

**Comment by royragsdale** [comment]
Closed and ported to [picoCTF-Web](https://github.com/picoCTF/picoCTF-web/issues/48) the actively mainted version.
