### ISSUE TITLE
Test for Unicode Support

### ISSUE THREAD

**Issue by GroundPound** [picoCTF/picoCTF-Platform-2#20]
As mentioned in the discussion of #18 by @jburket , we'd like to add a test for Unicode support. The old test case for this can be found: https://github.com/picoCTF/picoCTF-Platform-2/pull/18/files#diff-2e9f88cc28661e9c636159b830c38059L311

**Comment by cganas** [comment]
What is the goal of these tests? I can imagine one that is very similar to deleted one that just tests general things. Another option would be to rerun the tests with different templates that have many unicode laden fields.

I don't think it is the kind of test that benefits from general testing. I'd argue all or nothing. If we ever run into problems I don't think it will be logging in with a new user or something very trivial as Python3.4/Mongo handles unicode fine.

**Comment by GroundPound** [comment]
I think the greater concern is the interaction with non-Python systems. Imagine someone makes a change such that shell accounts have the user name of the team. Changing the templates to have some Unicode sounds like the right way to go.

**Comment by GroundPound** [comment]
Another case where it could come up is the encoding used in the SQL database. It would be useful to have something like this for regressions.
