### ISSUE TITLE
Voluptuous Validation Schema Exception Handling 

### ISSUE THREAD

**Issue by cganas** [picoCTF/picoCTF-Platform-2#24]
When the API validates schema's it handles exceptions in a general way that can hide the actual issue.

For example:
```python
    Required('username'): check(
        ("Usernames must be between 3 and 20 characters.", [str, Length(min=3, max=20)]),
        ("This username already exists.", [
            lambda name: safe_fail(get_user, name=name)is None and 1/0 == 0])
    ),
```

This snippet will raise a WebException with the message "This username already exists."
As a result, the underlying division exception will not be logged.

**Comment by jburket** [comment]
Is this issue ready to be closed?

**Comment by cganas** [comment]
Yes, should be good to go.
