### ISSUE TITLE
Scoreboard Not Updating

### ISSUE THREAD

**Issue by nanductf** [picoCTF/picoCTF-Platform-2#26]
Scoreboard always reflecting "No teams have scored any points yet." even when I submitted solutions for 3 teams and all teams had 10 points. However it reflects the team score in team-page and graph is also reflecting appropriately

I even tried raising score for the second and third team, still no big change in scoreboard.

**Comment by nanductf** [comment]
python3 daemon_manager.py cache_stats -i 300

The above shown command helped, however the point here is when we are integrating the entire stuff with the good and working API framework, should we not think about including this as part of the framework, rather than forking this as a separate process. 

This will help in having this in an integrated fashion and avoid followups. 

Just thinking out aloud.

**Comment by GroundPound** [comment]
The documentation for enabling the scoreboard will be added as a part of #11 .
