### ISSUE TITLE
Setting Up On Digital Ocean

### ISSUE THREAD

**Issue by JacobEdelman** [picoCTF/picoCTF-Platform-2#28]
I've been trying to set this up on Digital Ocean for HSCTF but I've had trouble doing so. After spending a large amount of time trying to get vagrant installed when I finally did it started throwing syntax errors on the vagrant file. Is there any easy way to set this up on a VPS like Digital Ocean?

**Comment by GroundPound** [comment]
The Vagrant environment is not meant for production setups, from a security standpoint alone. Additionally running a VM inside Digital Ocean's VM will degrade performance substantially. You should use the Vagrant setup script as a guide to how to configure your own server. Another user discussed doing so in another issue: https://github.com/picoCTF/picoCTF-Platform-2/issues/25#issuecomment-85290294

I'll create an issue for more documentation on production deployments. If there are specific things you'd like to see documented, please let us know or create issues for them.

**Comment by JacobEdelman** [comment]
Okay, thanks!
