### ISSUE TITLE
Production Environment Setup Documentation

### ISSUE THREAD

**Issue by GroundPound** [picoCTF/picoCTF-Platform-2#29]
The current documentation can give the impression that Vagrant should be used to deploy on a remote server hosted by a cloud service such as AWS or Digital Ocean. See https://github.com/picoCTF/picoCTF-Platform-2/issues/28 . We should add a specific documentation on how to deploy the picoCTF Platform without Vagrant.

**Comment by GroundPound** [comment]
Duplicate of #11 .

**Comment by failedxyz** [comment]
Can you add this to the documentation?

**Comment by GroundPound** [comment]
We plan to add this documentation. I decided this is very similar to #11 which should include this as well.
