### ISSUE TITLE
Development Deploy Script Cleanup

### ISSUE THREAD

**Issue by GroundPound** [picoCTF/picoCTF-Platform-2#3]
Originally reported by @dbrumley:
> Devploy mixes staging and deployment, alters files within the git repo instead of locally (in a staged area), and uses hard coded paths (which must be changed on each line). Devploy should be rewritten as a makefile that:
•Sets up a proper local staging area.
•Uses pathnames defined once at the top of the file
•does not mix building the site and deploying the site under /srv
•does not mess with mounted files under the git repo.

**Comment by royragsdale** [comment]
Closed and ported to [picoCTF-Web](https://github.com/picoCTF/picoCTF-web/issues/49) the actively maintained version.
