### ISSUE TITLE
Move Folder Configuration to `config.py`

### ISSUE THREAD

**Issue by GroundPound** [picoCTF/picoCTF-Platform-2#31]
We want to define the `static`, `problems`, and `graders` folders in `config.py`. `devploy` will have to be changed to reference the configuration correctly. This issue is a follow-up to the confusing discussed in #25 .

**Comment by royragsdale** [comment]
Closed as a legacy enhancement and development shifting to [picoCTF-platform](https://github.com/picoCTF/picoCTF-platform).
