### ISSUE TITLE
Cannot Find Problem Instances

### ISSUE THREAD

**Issue by failedxyz** [picoCTF/picoCTF-Platform-2#32]
[Question]
I used the example problem, but for some reason it's looking for a non-existant `Hidden message` file. As a result the site is giving me "Cannot find problem instances." If you need more details about my setup, I can relay it here.

**Comment by jburket** [comment]
Howdy! Sorry you're running into issues. This error usually comes up when no auto-generated problem instances have been generated for problems that have been loaded. Did you run `python3 api_manager.py autogen build 100` after loading in the problems?

**Comment by GroundPound** [comment]
@failedxyz Did Jonathan's solution help?
