### ISSUE TITLE
Team passwords are stored in plain text

### ISSUE THREAD

**Issue by JacobEdelman** [picoCTF/picoCTF-Platform-2#33]
The team passwords are stored in plain text. The user passwords are properly hashed.

**Comment by cganas** [comment]
This was a design decision. Having team passwords in plain text prevents users from forgetting their team password after registration as it is displayed on the team page. We argue that convenience is worth the small security trade-off. Note that you can not do anything harmful to a team by knowing the password.

**Comment by JacobEdelman** [comment]
Okay, thanks.
