### ISSUE TITLE
Private IP Address

### ISSUE THREAD

**Issue by Schmedley** [picoCTF/picoCTF-Platform-2#35]
I am currently setting up and customizing the platform. Although I am able to access the website and login to the team page at `127.0.0.1:8080`, when I try to access it from my private IP address: `192.168.1.221:8080`, I am unable to login to the team page since it simply redirects me back to the login page. Is there anything I need to configure to be able to successfully access the website at my private IP address?

**Comment by jburket** [comment]
Howdy! I believe this is probably a problem with the domain for the session cookie being set to 127.0.0.1 in the config.py. If you edit the line "api.app.session_cookie_domain = "127.0.0.1"" in /api/api/config.py to reflect your new ip, this should hopefully fix your problem.

**Comment by jburket** [comment]
Over the next week I will be adding a whole bunch more documentation to the platform. I am going to keep this issue around (assuming this is a config file issue) so that I make sure we address it in the documentation.

**Comment by Schmedley** [comment]
I made this change and it solved my issue. Thank you very much!

**Comment by dannyqiu** [comment]
It also works when you set the session cookie to None. Is there any harm in doing this?
`api.app.session_cookie_domain = None`

**Comment by GroundPound** [comment]
Flask dictates this behavior. The [documentation](http://flask.pocoo.org/docs/0.10/config/) states that if `session_cookie_domain` is `None`, then all subdomains of `server_name` can read and write the cookie. I don't think we set `server_name`. While I'm not sure what happens when `server_name` is also unset, the documentation implies it bases it off the domain in the request.

**Comment by royragsdale** [comment]
This is question was resolved in #39.  Thank you for highlighting it so that it could be added to the documentation.

[GettingStarted.md](https://github.com/picoCTF/picoCTF-Platform-2/blob/master/GettingStarted.md) is a great resource
