### ISSUE TITLE
Serve Third-Party JavaScript Locally

### ISSUE THREAD

**Issue by GroundPound** [picoCTF/picoCTF-Platform-2#4]
Originally reported by @dbrumley:
> bootstrap and jquery should be served locally, unless at deployment their is a bandwidth issue. The reason is you cannot do development or deployment without internet access. 

At the very least we should modify it such that the development environment serves them locally if not the production environment. The Jekyll configuration already does something similar for analytics.

**Comment by royragsdale** [comment]
Closed and ported to [picoCTF-Web](https://github.com/picoCTF/picoCTF-web/issues/2) the actively maintained version.
