### ISSUE TITLE
reCAPTCHA Verification Broken

### ISSUE THREAD

**Issue by coreymason** [picoCTF/picoCTF-Platform-2#41]
Your reCAPTCHA validation does not work. In my own version of this platform, I have fixed your validate function and updated it (along with the registration coffeescript) to work with Google's reCAPTHCA v2.

I'd be happy to submit a pull request to master (or whichever branch you direct me to) with the fix and update for review. Just let me know.

**Comment by cganas** [comment]
I would love to take a look at a pull request if you have one! reCAPTCHA was something we testing initially but never ended up using in production so it is very possible an issue went unattended.
