### ISSUE TITLE
SMTP Configuration Settings

### ISSUE THREAD

**Issue by coreymason** [picoCTF/picoCTF-Platform-2#42]
There appears to be SMTP configuration settings in both config.py and utilities.py. Furthermore, unless I'm missing something, I don't see the SMTP settings in config.py being used anywhere (the settings in utilities.py are used though). Perhaps, these settings should be consolidated or am i missing something?

Also, the getting started documentation in #39 states this should be set in config.py but as i stated, I don't see those being used anywhere.

**Comment by cganas** [comment]
The SMTP configuration options in `config.py` actually set the relevant fields in `utilities.py`. This is done for many of the options.
