### ISSUE TITLE
Redirecting back to login page after logging in?

### ISSUE THREAD

**Issue by bobacadodl** [picoCTF/picoCTF-Platform-2#44]
I am having an issue with the website, when after registering an account, I try to log in and it doesn't work.

If i enter an incorrect username or password, it behaves exactly as expected.

However, if I enter valid credentials, the page redirects to the Team page for a second, then redirects back to the login page for no apparent reason.

I am running picoCTF on an ubuntu machine (Ubuntu 14.04 x86_64), and installed the dependencies manually. All the regression tests successfully passed. I am pretty sure it is running in an OpenVZ environment.

**Comment by jburket** [comment]
I suspect you are having an issue with the cookie settings. Checkout this issue (https://github.com/picoCTF/picoCTF-Platform-2/issues/35) for more details. We also have some documentation that we have been developing that might be helpful (https://github.com/picoCTF/picoCTF-Platform-2/blob/documentation/GettingStarted.md). It has not been finalized yet, but it still may be useful to you as you set things up.

**Comment by bobacadodl** [comment]
Wow, this documentation is extremely helpful. Wish I'd seen that sooner! Hopefully that will solve my issue...

**Comment by bobacadodl** [comment]
Got it working! Thanks for the help :+1:

**Comment by GroundPound** [comment]
The documentation is currently sitting in Pull Request #39 , so don't feel bad for missing it! As soon as @cganas is done reviewing it we'll merge it in.
