### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by bobacadodl** [picoCTF/picoCTF-Platform-2#45]
How should we go about adding a favicon to the site?

**Comment by failedxyz** [comment]
Simplest way is to add a `<link rel="icon" href="/path/to/favicon.ico" />` in the `/web/_includes/head.html`.

**Comment by GroundPound** [comment]
We should leave this issue open so that the documentation can be updated accordingly.

**Comment by royragsdale** [comment]
Hi all, thank you for the question, and @failedxyz for the nice simple recommendation.
In f473677a4ddbde76755bf332c4dd76dd86cc18b5 I added this to [GettingStarted.md](https://github.com/picoCTF/picoCTF-Platform-2/blob/master/GettingStarted.md) to ensure others can find this information in the future.
