### ISSUE TITLE
How to make all team eligible?

### ISSUE THREAD

**Issue by mabdi** [picoCTF/picoCTF-Platform-2#50]
How to make all teams eligible?

**Comment by cganas** [comment]
Hello! To make all teams eligible from the API's perspective you can add `params["eligible"] = True ` [here](https://github.com/picoCTF/picoCTF-Platform-2/blob/master/api/api/team.py#L96). However, I'd encourage you to use the newest [platform](https://github.com/picoCTF/picoCTF-platform). 

Development and support for this version has ceased.
