### ISSUE TITLE
Jekyll fails to install with ruby v.1.9.3

### ISSUE THREAD

**Issue by sachinkamath** [picoCTF/picoCTF-Platform-2#51]
Jekyll installation throws an error when `vagrant up` is executed.

**Comment by mabdi** [comment]
try `$ sudo apt-get install jekyll`

**Comment by sachinkamath** [comment]
That didn't work for me either.

The problem is the installer script tries to install the v.3 of Jekyll along with ruby 1.9.3. You need to install a previous version of jekyll for the gem installation to succeed when you are running 1.9.X

The solution is : 
`gem install jekyll -v 2.5.3`

**Comment by royragsdale** [comment]
Hi @sachinkamath thank you for the recommended solution. This has been implemented in 1f359f3d5a49e5fc2909775cdab6ed534cc0092f. `vagrant up` should work now.
