### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by jmb1304** [picoCTF/picoCTF-Platform-2#55]
I followed the tutorial on your github page on how to setup picoctf but whenever i try to load the page in my web browser, it says 403 Forbidden. This is extremely frustrating along with the fact that your scripts don't even work on the vm. I had to install jekyll myself. Please fix this soon. I wanted to use this for a project because it seemed like a wonderful piece of software but does not work.

**Comment by t94j0** [comment]
I am getting the same error and would love some guidance.

**Comment by royragsdale** [comment]
hi @jmb1304 and @t94j0 , I believe this is most likely as a result of the dependency issue that was identified in #51.

This has been addressed in the latest commit, if you would be willing to pull and try again following a `vagrant destroy`.

**Comment by t94j0** [comment]
That fixed it perfectly. Thanks!

**Comment by royragsdale** [comment]
@t94j0 thank for for the confirmation. Closing now.
