### ISSUE TITLE
Password problems

### ISSUE THREAD

**Issue by t94j0** [picoCTF/picoCTF-Platform-2#57]
I just moved from creating all of my problems in my development Vagrant environment to a production environment. In my new production environment, I can't log in as any users. I can create the accounts perfectly and see them in the Mongo database, but when I try to log in through the front-end, the account automatically logs out and goes to the login page. Anyone have similar problems or know of a potential solution to this?

**Comment by royragsdale** [comment]
Hi @t94j0 one thing that might cause wonky behavior like this is stale cookies. You could try clearing them, or logging in from a private browser session like chrome's incognito.

**Comment by cganas** [comment]
Make sure to change the flask cookie domain. Also if for whatever reason you are using `localhost` you'll have problems with cookies. Use `127.0.0.1` in virtually all cases.

**Comment by t94j0** [comment]
@cganas You are 100% correct. I forgot to change the flask cookie domain. Thanks a lot.

**Comment by royragsdale** [comment]
@t94j0 glad we could get that fixed. Can you confirm #55 is no longer an issue for you?
