### ISSUE TITLE
Problem Numbers

### ISSUE THREAD

**Issue by GroundPound** [picoCTF/picoCTF-Platform-2#6]
Originally reported by @dbrumley. We would like the game to assign numbers to problems and additionally display the number of problems currently solved to the user to help instructors integrate the platform into their coursework. At this time it's unclear when the mapping from problem name to number is created and where it is stored. Should it be something that we add to the problem JSON specification?

**Comment by cganas** [comment]
I don't quite understand. Do you mean there should be an additional number attached to a problem that is displayed as part of its title? e.g. enumerating the problems 1, 2, ...
What does it mean for a user to see the number of problems currently solved, like 10/32 problems? 

I would imagine these kinds of features would be enhancements made to the classroom page, not to the general user's interface.

**Comment by GroundPound** [comment]
Here was the original report: https://github.com/picoCTF/picoCTF-Platform-1/issues/16

I believe your interpretations are correct.

**Comment by dbrumley** [comment]
Yes, problems should be numbered. In a classroom teachers want to ask about a particular problem, and having a number is the easiest. Students also want to know "how many have I solved".  This would be to both the classroom and the user interface. A teacher couldn't ask about problem 5 if the student didn't know what problem 5 was.

**Comment by cganas** [comment]
To prevent the numbers from changing this would have to be something that is automatically added to the problem specification when loaded as the API is able to disable problems. For example, you wouldn't want to affect problems 6 through 10 because you disabled 5. It is definitely doable with some caution towards continuity edge cases.

I think it would be a useful visualization to show the team how many they have solved out of the total available problems but I do not like the idea of giving per user stats outside of the classroom.

I think you could achieve the same effect by having it show per user in the classroom interface and per team on the team page.

**Comment by dbrumley** [comment]
This doesn't make sense to me from a user perspective. The players see the problems in a linear order; they would expect the position to indicate a number (and for other players to have that same number).  Why is it hard-coded as part of the problem definition? Conceptually it seems part of the UI design.

Teachers should be able to see per-user stats. I think admin's (we really could benefit potentially from finer-grained permissions, btw) would want to see the overall lay of the land.  For example, I bet everyone was wondering during the contest whether a particular problem had been solved by anyone yet; you shouldn't need database access to answer that question.

I think we can show per-team on the team page, but I don't see why it should matter much to have the ability to show both the team count and the number each player solved.  I think the motivation by seeing a number moved up outweighs concerns over someones feelings hurt by seeing how many problems they actually have solved.

**Comment by cganas** [comment]
Based on how problem progression works, with weightmaps, what might be my problem 5 might not be another team's problem 5. I believe adding numbers could introduce a lot of confusion in this case. You can imagine playing the game and completing problem 3 and you unlock problems 6, 8, and 10. The user would be confused as to why they don't have the intermediate problems.

If you don't define a global ordering at the database level there are operations that could be run during the competition that would introduce continuity "errors." And it would be a whole other issue if we wanted to support selecting a subset of problems to be active for a competition as the numbering would have to somehow be both fluid based on the subset of problems selected while being consistent.

As far as the per user stats, I don't believe in putting per user stats on the team page. It's a competition against other teams and I don't think individual statistics are meaningful at the team level.

As far as admin accounts and finer grained permissions, I'll create an issue for that soon. I have some ideas that need to be fleshed out but encompass the points you brought up.

**Comment by dbrumley** [comment]
Does it make sense for the problems in the game not to reflect the problems on the board? It seems like users should know which problems they have missed in either view (and in general).

**Comment by cganas** [comment]
I don't understand. Are you referring to the enumeration from the game? https://github.com/picoCTF/picoCTF-Platform-2/commit/2e118ae99cea702d73a1333ccf290c9dd82c1ae0#diff-c85b52c8a2bdc46b95a3982b719d879eL43

That wouldn't exist anymore. The visualization I'll propose would indicate there are problems you have missed/not unlocked yet but it would not number them for the reasons above.

**Comment by dbrumley** [comment]
I'm not referring to specific code. I talked to Jonathan a bit here. My understanding is that there is no total ordering, and that the ordering given is based on unlocking. Jonathan's proposal, which makes sense, is to give all problems a total ordering but display in the alt viewer which problems are locked.  

In your example, if two players have different problem 5s, this seems wrong.  If two players have unlocked all problems, they shouldn't have two different lists on their screen.  A quick glance doesn't seem to indicate this is an issue; ordering seems to be decided by mongo.

**Comment by jburket** [comment]
To elaborate on what I was proposing, we could do the following:
1. From the beginning, all problems are listed on the problems page, but ones you haven't unlocked are grayed out, or something similar. That way the problems list never actually changes as problems are unlocked, solving many of the numbering issues.
2. Problems list what the conditions are to unlock that problem. For example, a locked problem might say something like "Solve 2 out of X, Y, and Z to unlock". This would be a bit tricky to derive from the weightmap right away, but we could probably come up with something, or modify the weightmap format.

In any case, this would make the ordering aspect less confusing and explicitly expose the problem unlock conditions. It doesn't solve the issue of what to do if a problem is added or revoked during a competition, though. It may be that we are willing to have the numbering change in this case.

**Comment by GroundPound** [comment]
The other question is when are the problem numbers assigned. Are they defined in the `problem.json` or assigned by the import script as they are added to the database? I see advantages to each based on how often we envision people sharing challenges between competitions.

**Comment by royragsdale** [comment]
Now tracked on [picoCTF-web](https://github.com/picoCTF/picoCTF-web/issues/53)
