### ISSUE TITLE
Teacher CSV Export

### ISSUE THREAD

**Issue by GroundPound** [picoCTF/picoCTF-Platform-2#7]
Originally reported by @dbrumley:

> It would be good to be able to export the current view of students as a CSV file (with timestamp). The purpose would be to allow a teacher to dump information of student point values so far, e.g., so they can keep track of picoctf progress as if it were an assignment. Bonus if we can also log which problems a student has solved with timestamp.

**Comment by royragsdale** [comment]
Closed and ported to [picoCTF-Web](https://github.com/picoCTF/picoCTF-web/issues/51) the actively maintained version.
